- ipu-plugin/go.mod
- ipu-plugin/go.sum
- ipu-plugin/ipuplugin/cmd/rootcmd.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
This PR adds the code to integrate the communication setup channel functionality into the ipu-plugin.
> Integrate communication setup channel with ipu-plugin

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Removes error return when not a valid PF.
> Avoid returning an error on invalid PF

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Do not return an error  if address is set on the APF
> Do not return an error if address is set on the APF

- ipu-plugin/Makefile
- ipu-plugin/images/Dockerfile
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
This PR updates the paths in the ipu-plugin to replace the linux_networking recipe artefacts.
> Updated paths from linux_networking to rh_mvp

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
The rules to preconfigure the FXP should only be applied when the VSP is initialised in IPU mode. This is due to the reliance on the p4rt-client which can only be run in the IPU mode at the moment.
> Preconfigure the FXP only in IPU mode

- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
This PR removes a const struct and adds a check to return an error via gRPC if no VFs are initialized on the host.
> Few small cosmetic changes

- e2e/artefacts/k8s/vsp-ds.yaml
limit plugin daemonset to run on worker nodes only using node anti-affinity.
> limit plugin daemonset to run on worker nodes only

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
This adds the FXP handler to avoid running the p4rtclient during unit tests.
> Fix lifecycleservice unit test

- p4sdk/images/entrypoint.sh
This should some error messages shown in the log when we are starting infrap4d inside the container.
> Fix logging error messages when starting infrap4d in container

- ipu-plugin/pkg/ipuplugin/deviceplugin.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
Added support for GetDevices, when invoked from host side, to return list of VFs. 
With this, GetDevices can get invoked when VSP runs in host and IPU.
> Added support for GetDevices, when invoked from host side, to return list of VFs.

- ipu-plugin/pkg/ipuplugin/deviceplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Change to use internal interface->enp0s1f0d4(d4), on ACC, for host<->ACC communication. Previously d2 interface was used on ACC, which was meant for external network interface. Using external interface D2 also caused issue when fixed(unique) MAC was set thro fixboard script, since VSP checks for vportid in MAC. Since above change would reduce the number of APFs returned by GetDevices by 1, value of ->acc_apf in node-policy has been increased to 16.
> Change to use internal interface->enp0s1f0d4(d4), on ACC, for host<->ACC communication

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/utils/utils.go
When VSP gets started, if host IDPF net devices are not there, VSP
will do rmmod/modprobe to bring up those those net devices.
> Change to bringup host IDPF netdevices

- e2e/artefacts/k8s/vsp-ds.yaml
- ipu-plugin/ipuplugin/cmd/rootcmd.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
- ipu-plugin/pkg/utils/utils.go
Changes for removing args passed in vsp-ds.yaml.
We can still pass args(for debugging purpose). But for now, except for log level, rest have been removed. 
Also code to find vsi for bridge interface(on ACC side) has been added.
> Changes for removing args passed in vsp-ds.yaml.

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Randomize last 2 bytes(5th and 6th) of MAC address in node policy.
> Randomize last 2 bytes(5th and 6th) of MAC address in node policy.

- e2e/artefacts/k8s/vsp-ds.yaml
- ipu-plugin/images/Dockerfile
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
It can take time for network-manager's state for each interface, to become activated, when IP address is set, which can cause the IP address to not stick. Removing the host and acc comm channel interfaces out of network-manager's mgmt.
> Fix for->IIC-364: After host reboot, host connection to ACC is lost

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
Option2: First set IP address, sleep for a while, and check
if interface is activated thro nmcli. Retry for few times,
until it succeeds or times out. Also had to add connection,if profile does not exist.
> Set IP for host ACC comms channel

- ipu-plugin/pkg/ipuplugin/bridgeport.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
Changes to ipu-plugin with OVS calls in-place.
Also prevents IMC reboot, when APF count doesnt match during Init.
Basic Host-VF to Host-VF ping test works.
Other use-cases testing WIP.
>     Changes to ipu-plugin with OVS calls in-place.

- ipu-plugin/images/Dockerfile
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Resolves-> https://jira.devtools.intel.com/browse/ISSE-71
Handles both update cases below:
Case1(P4 package update): Changes to detect if pkg file needs to be updated thro IMC reboot.
In case, where ipu-plugin has a different P4 package,
compared to what is on IMC using md5sum.
With this PR, P4 package update will be handled.
Case2(Node policy update): Also handles case, where load_custom_pkg.sh has different entries in ipu-plugin versus on IMC.
So node policy update also gets handled.
>   Changes to detect if pkg file needs to be updated thro IMC reboot.

- ipu-plugin/go.mod
For compatibility with downstream, revert the go version.
> revert go version

- e2e/artefacts/k8s/vsp-ds.yaml
- ipu-plugin/pkg/ipuplugin/bridgeport.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
- ipu-plugin/pkg/ipuplugin/ovsbridge.go
- p4sdk/Makefile
- p4sdk/buildkit.toml
Changes to ensure that Peer2Peer P4 rules, will get added, independant, of order of deployment of VSP(ipu-plugin) on x86-host and ACC. If ipu-plugin's Init function gets invoked on ACC, prior to getting invoked on x86, then host VFs will not be setup yet. In that case, peer2peer rules can get added in CreateBridgePort or CreateNetworkFunction. Moved Deletion of P4 rules(such as PeerToPeer) at the point, where pod gets deleted, this increases the timeout period to greater than default 30 seconds, so updated vsp-ds.yaml file with increased timeout. And few misc fixes part of this PR.
> Add Peer2Peer P4 rules independant of order of deployment, and other fixes.

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Change to replace manual step(used by redhat, where ipu_port1_setup.sh script is used).
By creating post_init_app.sh script, through ipu-plugin. post_init_app.sh, gets invoked by IMC software, after ipumgmt daemon,  
starts running. post_init_app.sh, creates this script->port0-setup.sh which runs in the background, and waits until D4 interface gets created on ACC. Once D4 interface gets created on ACC, port0-setup.sh uses devmem command to add D4 interface to the forwarding VSI group 1.
> Change to replace manual step(used by redhat, where ipu_port1_setup.sh script is used).

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Fix for PR->292. D5 interface is used for primary networking.
Also needed to add a sync after files get removed, before
re-creating port-setup.sh and port-setup.log files.
> Fix for PR->292. D5 interface is used for primary networking.

- ipu-plugin/ipuplugin/cmd/rootcmd.go
- ipu-plugin/pkg/ipuplugin/bridgeport.go
- ipu-plugin/pkg/ipuplugin/bridgeport_test.go
- ipu-plugin/pkg/ipuplugin/deviceplugin.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
- ipu-plugin/pkg/types/types.go
- ipu-plugin/pkg/utils/utils.go
Changes for Host VFs and num of APFs increased to 48, to accomodate 16 Host VFs.
Pre-defined range of ACC APF interface indexes allocated for various usages like(Host VFs, NF PRs, NFs(for ingress/egress)). Added changes to use AccApfInfo type for mac-list and intf-name list. Basic sanity test for Init->SetupAccApfs and GetDevices works as expected.
Changes to run devmem commands to add 48 ACC APFs to forwarding group one. By default only 16 ACC APFs are added to forwarding Group one. Function->AddAccApfsToGroupOne added to ipuplugin's Run function.
Changes tested for init, getDevices, CreateBridgePort, DeleteBridgePort, host-VF-to-host-VF(ping test). With CreateNetworkFunction, and DeleteNetworkFunction works, and verified ping testing between external-client(CVL NIC) to NF's ingressMAC, …
> Changes to allow upto 16 Host VFs and num of APFs increased to 48.

- ipu-plugin/ipuplugin/cmd/rootcmd.go
Disable D6 check for linux P4 package.
> Disable D6 check for linux P4 package.

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Updates post_init_app.sh script, which installs
port-setup.sh script. port-setup.sh script,
will run devmem command for D5 interface, as soon as
D5 comes up on ACC, to enable connectivity. 
There is an intermittent race condition, when port-setup.log file, is
accessed(for file removal or any other case) by post_init_app.sh,
then later when nohup tries to stdout to that log file(port-setup.log),
there are file sync issues, either file is not updated or gets removed(if
it gets removed by post-init-app.sh.
For example, if port-setup.log gets removed, prior to nohup invoking
port-setup.sh script, then nohup does NOT invoke the script.
In order to circumvent this,
just allowing nohup to over-write port-setup.log. Also, to
make this more robust, added polling in post-init-app.sh, to check for …
> Installs script to run devmem command for D5 interface.

- ipu-plugin/ipuplugin/cmd/rootcmd.go
- ipu-plugin/pkg/ipuplugin/deviceplugin.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
- ipu-plugin/pkg/utils/utils.go
Change to use Go Dial api for ssh, for better error
messages, when ACC to IMC connection is down.
Make utils apis more go based.
Also reduce excessive logging in GetDevices(which gets called periodically by DPU).
> Better error handling in utils, and reduce logging in GetDevices

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
fxp-net_linux-networking P4 package has a predefined default action value which always forwards the packets to a fixed vsi_id, which is presumed to be the one assigned to the D5 interface. As the vsi_id assignments per inteface is dynamic (which can change per running instance), a change in D5's vsi_id could potentally break the D5 communication right after IPU init, where the P4 rules are still not programmed.
To address this issue, we update the rx_phy_port_pr_map table's default action with the correct vsi_id of D5 interface as part of the port init configuration procedures.
> Configure rx_phy_port_pr_map table's default action with D5's updated VSI ID

- ipu-plugin/pkg/ipuplugin/deviceplugin.go
Provide pci-address for host-side VFs.
Interface names are expected for IPU side.
Caching support added for GetDevices.
For the first call, we query the devices(on host or ACC) and cache it. For subsequent calls, we return cached list of devices. Caching helps in addressing the case, wherein, if host-VF is allocated for a pod, it is no longer available in host netnamespace, so doesnt show up under /sys/class/net, so we were returning 1 less device, but DPU's allocator still expects, the overall count of Host-VFs(even if one of them is in allocated state). DPU resource allocation, maintains its own list of total vs how-many VFs available.
> Provide pci-address for host-side VFs and caching support for GetDevices

- ipu-plugin/pkg/p4rtclient/p4rtclient.go
- ipu-plugin/pkg/p4rtclient/rh_p4client.go
- ipu-plugin/pkg/utils/utils.go
Address a possible incorrect VSI id usage scenario along with P4 rule add failure handle when a similar rule is already programmed or in place.
> Address Redhat Flow Test failure scenarios

- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/mocks_test.go
- ipu-plugin/pkg/p4rtclient/p4rtclient.go
- ipu-plugin/pkg/p4rtclient/rh_p4client.go
- ipu-plugin/pkg/types/types.go
- ipu-plugin/pkg/utils/utils.go
Using mutex, to serialize access to python client p4rtctl, when there are concurrent callers
to RunP4rtCtlCommand API in utils.go
Note::p4rtctl python client, uses fixed value(1 for election-id). So when they are concurrent
clients invoking it, p4 runtime server(infrap4d) throws error.
> Using mutex, to serialize access to python client p4rtctl

- ipu-plugin/pkg/ipuplugin/bridgeport.go
- ipu-plugin/pkg/ipuplugin/bridgeport_test.go
- ipu-plugin/pkg/ipuplugin/deviceplugin.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
- ipu-plugin/pkg/types/types.go
- ipu-plugin/pkg/utils/utils.go
Support upto 16 Host VFs(pods), with increase of netdevs on ACC(to 48) 
Supporting just 1 NF for TP. 
Needs debugging to support
more NFs(past the first 16 netdevs on ACC). Ping
from external client to NF ingress was not working
for higher order netdevs(like D16 onwards). 
Despite having function to use devmem commands to add all ACC netdevs to forwarding Group one.
> Support upto 16 Host VFs(pods), with increase of netdevs on ACC(to 48) 

- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
This is required to preserve ACC's D1 interface MAC address across package upgrades (from default to redhat).
> Align DPCP config rep_vport to be inline with default config

- ipu-plugin/pkg/ipuplugin/ipuplugin.go
Make firewall configuration specific to microshift cluster scope.
The vsp-plugin runs on both MicroShift and OpenShift clusters. Firewalld configuration is required only in the MicroShift cluster context. Verify the ipuMode and configure firewalld only when the vsp-plugin is running on an IPU.
> Make firewalld configuration specific to microshift cluster scope

- ipu-plugin/pkg/ipuplugin/bridgeport.go
- ipu-plugin/pkg/ipuplugin/bridgeport_test.go
- ipu-plugin/pkg/ipuplugin/deviceplugin.go
- ipu-plugin/pkg/ipuplugin/ipuplugin.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice.go
- ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go
- ipu-plugin/pkg/ipuplugin/networkfunctionservice.go
- ipu-plugin/pkg/types/types.go
- ipu-plugin/pkg/utils/utils.go
Increasing the number of APFs from 16 to 48 so that a max of 16 VFs can be supported
> IIC-559 Add support for 16 VFs
