intel/ipu-opi-plugins

ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go
Adding mode option to distinguish between host and ipu.
=> Added mode option

network_function/README.md, network_function/dockerfile, network_function/nf.c
First cut of network function dummy code
Signed-off-by: Paul Hough <paul.f.hough@intel.com>
=> Adding Network Function subdirectory

ipu-plugin/Makefile, ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go
- change IPU pluging to serve on unix socket as default to be compliant with DPU daemon
- fix golangci-lint timeout error
=> serve on unix socket as default

p4sdk/Makefile, p4sdk/README.md, p4sdk/images/Dockerfile
Adding P4 SDK container image build steps
=> add p4sdk container image build steps

.github/workflows/buildtest.yml, network_function/dockerfile, sriov_cni/Dockerfile.arm64, sriov_cni/Dockerfile.ppc64le
Add sriov_cni dir to the build test CI
=> Update buildtest & fix dependency issues

ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go, ipu-plugin/pkg/ipuplugin/lifecycleservice.go, ipu-plugin/pkg/types/types.go
Run selective grpc service based what mode the plugin is running.
=> ipu-plugin: run grpc service based on plugin mode

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Swap ip when for checking mode.
=> Swap ips when checking for mode

p4sdk/Makefile, p4sdk/images/Dockerfile, p4sdk/images/entrypoint.sh, p4sdk/images/es2k_skip_p4.conf.template
Run infrap4d from container image.
=> p4sdk: run infrap4d from container image

p4sdk/Makefile, p4sdk/images/Dockerfile, p4sdk/images/entrypoint.sh
update p4 container for testing with standalone container.
=> update p4 container image and entrypoint

p4sdk/README.md, p4sdk/images/Dockerfile, p4sdk/images/entrypoint.sh
Updated Dockerfile to install the required dependencies and run the infrap4d binary.
=> Updated p4sdk dockerfile to run infrap4d

ipu-plugin/README.md, ipu-plugin/ipuplugin/cmd/rootcmd.go
remove plugin mode option from cli args, determine the mode on runtime based on what platform the plugin is running.
=> remove plugin mode option from cli

network_function/nf.c
Signed-off-by: Paul Hough, <paul.f.hough@intel.com>
=> Creates 2 threads for full duplex NF

ipu-plugin/images/Dockerfile
We need openssh to run ssh commands to configure the fxp
=> Added openssh to run ssh commands from the container

ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/p4rtclient/p4rtclient.go, ipu-plugin/pkg/p4rtclient/rh_p4client.go
Handle rh_pkg specific fxp arp rules addition/deletion
=> handle rh_pkg fxp arp rules

ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go, ipu-plugin/pkg/ipuplugin/lifecycleservice.go, ipu-plugin/pkg/ipuplugin/lifecycleservice_test.go, ipu-plugin/pkg/p4rtclient/p4rtclient.go, ipu-plugin/pkg/p4rtclient/rh_p4client.go, ipu-plugin/pkg/utils/utils.go
Refactor reusable functions. It depends on PR #119
=> Refactor reusable functions

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Workaround added to preconfigure the FXP.
=> Adding functions to preconfigure the FXP

e2e/artefacts/fxp/README.md
A README.md file for bash scripts
=> Added README.md file for bash scripts to program the FXP

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
This PR adds the following changes:
- edit the ssh function call in the init to avoid adding EOF at the end of the loadcustompackage.sh
- append the python script to configure the acc to the end of pre_init_app.sh
@ahalimx86  Pushing the changes here as I cannot push to your fork.
=> Editing the sshfunc call to avoid adding EOF at the end of the load custom script

ipu-plugin/pkg/ipuplugin/bridgeport.go, ipu-plugin/pkg/ipuplugin/bridgeport_test.go
This PR adds outer and inner tag to bridge port call.
=> Adding outer and inner vlan tags to bridge port

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Updating the required number of APFs on the IPU. For demo, we will use only 8. Beyond demo, this can be increased.
=> Update APFs number

ipu-plugin/pkg/ipuplugin/bridgeport.go, ipu-plugin/pkg/p4rtclient/rh_p4client.go
This PR fixes the table name in p4rt-client - the previous rule had the wrong table name. Also this PR moves the creation of the outer vlan outside of the inner vlan creation function. This also adds the possibility to add the outer vlan interface to the bridge. Previously - because the outer vlan interface was not up, the call to CreateBridgePort would have failed.
=> Fix table name in p4rt-client

e2e/artefacts/k8s/nad.yaml, e2e/artefacts/k8s/pod-nf.yaml
add sample pod spec for NF and udpate NAD for it to use.
=> add sample pod spec for NF

ipu-plugin/Makefile
fix make imagex build errors for multi-arch image build.
=> fix broken multi-arch image build for ipu-plugin

ipu-plugin/pkg/ipuplugin/ipuplugin.go
fix missing p4rtbin initializer
=> fix missing p4rtbin initializer

e2e/artefacts/k8s/p4sdk-ds.yaml, e2e/artefacts/k8s/vsp-ds.yaml, ipu-plugin/pkg/ipuplugin/deviceplugin.go, p4sdk/images/Dockerfile, p4sdk/images/entrypoint.sh
- add portMux vsi in ipu-plugin container args
- fix p4 image entrypoint startup issues
=> fix p4 image entrypoint  and change port mux vsi

ipu-plugin/pkg/ipuplugin/deviceplugin.go, ipu-plugin/pkg/utils/utils.go
After enabling VFs on host, changed the way to verify, if those VFs came up fine. Previous way of ssh from host to IMC, to run cli_client is not reliable, since customer config may not support host to IMC connection.
=> After enabling VFs on host, changed the way to verify.

ipu-plugin/Makefile, ipu-plugin/images/Dockerfile, ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/ipuplugin/bridgeport.go, ipu-plugin/pkg/ipuplugin/deviceplugin.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go, ipu-plugin/pkg/ipuplugin/lifecycleservice.go, ipu-plugin/pkg/ipuplugin/linuxbridge.go, ipu-plugin/pkg/ipuplugin/networkfunctionservice.go, ipu-plugin/pkg/ipuplugin/ovsbridge.go, ipu-plugin/pkg/p4rtclient/p4rtclient.go, ipu-plugin/pkg/types/types.go, ipu-plugin/pkg/utils/utils.go, p4sdk/Makefile
Changes for Services-> LifeCycleService, DevicePlugin, BridgePort, and NetworkFunction, 
for use with linux-net package, and new design. P4 apis to be merged. Basic sanity test for CBP(CreateBridgePort), DBP, CNF(CreateNetworkFunction) and DNF work fine.
=> Changes for ipu-plugin with linux networking package, and new design.

ipu-plugin/Makefile, ipu-plugin/buildkit.toml, ipu-plugin/images/Dockerfile, p4sdk/Makefile, p4sdk/images/Dockerfile
* Cross compile changes to compile p4sdk container on x86 for arm
* Moving ipu-plugin from Alpine to redhat
=> Changes for cross compile dockerfile

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Node policy update for P4 lag rules
=> Node policy update for P4 lag rules

ipu-plugin/Makefile, ipu-plugin/buildkit.toml, ipu-plugin/images/Dockerfile, p4sdk/Makefile, p4sdk/images/Dockerfile
This reverts commit 4cacefea4a9e51a8741d5333259b18eec326947c.
=> Revert "Changes for cross compile dockerfile (#244)"

ipu-plugin/Makefile, ipu-plugin/buildkit.toml, ipu-plugin/images/Dockerfile, p4sdk/Makefile, p4sdk/images/Dockerfile
* Adding iproute2 for ip netns
* Making p4sdk cross compile changes
=> Dockerfile changes

ipu-plugin/pkg/ipuplugin/ovsbridge.go
The way ps was used it not compatible with RHEL based containers. This patch rewrites the function to behave in the same way without relying on ps.
=> Fix ps usage

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
=> Revert PRs-> 293 and 292

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
In order to handle RHEL ISO install use-case, where ACC reboots(post install),
independant of IMC, port-setup script will be running
as daemon, so anytime ACC goes down(it will get detected), so that devmem commands
will get re-run, when ACC comes up. Based on design, atleast 1 or utmost 2 instances
of port-setup can be running as daemon.
Addresses JIRA: https://issues.redhat.com/browse/IIC-502
=> Run port1-setup script as daemon, to handle RHEL ISO install use-case, where ACC reboots independently.

ipu-plugin/pkg/ipuplugin/ipuplugin.go, ipu-plugin/pkg/utils/utils.go
Correcting exec cmd
decreasing wait time of p4rt server port before erroring out to 20 secs
=> Correcting exec cmd of p4rt

ipu-plugin/pkg/ipuplugin/lifecycleservice.go
Fixed issue in port-setup.sh, to start second port-setup daemon, only when required. 
Removed port-setup*.log files upfront.
Also optimised sleep interval, to minimize any concurrency issue, when using cli-client tool.
=> Fixed issue and optimized port-setup.sh 

ipu-plugin/Makefile, ipu-plugin/go.mod, ipu-plugin/images/Dockerfile, ipu-plugin/ipuplugin/cmd/rootcmd.go, ipu-plugin/pkg/utils/utils.go
Misc fixes to fix the build of ipu-plugin, 
and also to fix issue, related to testing in non-cluster enviornment.
=> Misc fixes to fix the build of ipu-plugin.

ipu-plugin/pkg/ipuplugin/lifecycleservice.go, ipu-plugin/pkg/p4rtclient/p4rtclient.go, ipu-plugin/pkg/utils/utils.go
Delete FXP default rule during ipu-plugin triggered primary network configuration
=> Delete FXP default rule during ipu-plugin triggered primary network configuration

ipu-plugin/Makefile, ipu-plugin/pkg/p4rtclient/p4rtclient.go, ipu-plugin/pkg/p4rtclient/rh_p4client.go, ipu-plugin/pkg/utils/utils.go
Address a race condition which could have potentially impacted the p4rt-ctl add-entry or del-entry operations.
=> Address a race condition which could have potentially impacted the p4rt-ctl add-entry or del-entry operations.

ipu-plugin/pkg/infrapod/bindata/vsp-p4/99.vsp_p4.yaml, p4sdk/Makefile, p4sdk/images/Dockerfile, p4sdk/images/entrypoint.sh, p4sdk/images/es2k_skip_p4.conf.template
* Copying P4_NAME artifacts to /opt instead of /opt/p4 because that path gets mounted and disappears
* Adding new make target called imagex_podman which uses buildah instead of buildx
=> Mounting PVC in Daemonset of P4

ipu-plugin/pkg/ipuplugin/deviceplugin.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go, ipu-plugin/pkg/ipuplugin/lifecycleservice.go, ipu-plugin/pkg/p4rtclient/p4rtclient.go
Fix P4 rules to adapt D5 to D1 interface change for Redhat primary network access.
=> Fix primary network P4 rules to adapt D5 to D1 interface change

ipu-plugin/pkg/firewall/firewall.go, ipu-plugin/pkg/ipuplugin/ipuplugin.go
Enable firewalld at ACC with restricted access to allow only all the internal and p4 communication
=> Enable firewalld at ACC with restricted access
